server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name reloved.digital www.reloved.digital _;

    root /var/www/waitlist;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
